neoForge {
    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

group = mod_group_id

dependencies {
    implementation "curse.maven:architectury-api-419699:5786327"
    implementation "curse.maven:ftb-library-forge-404465:7746959"
    implementation "curse.maven:ftb-teams-forge-404468:7878281"
    implementation "curse.maven:ftb-quests-forge-289412:7878289"
}